API tests
krssw/Automation-Practice pull request #2
Opened 2024-08-01 18:56 UTC by krssw

2024-08-05 06:58 UTC, al-kai requested changes

2024-08-05 06:58 UTC, al-kai commented on src/test/resources/features/add_user.feature
> +Feature: Add user to list of users
I think that adding, removing, updating user etc. are not features actually but rather test scenarios regarding User. So I'd suggest creating one feature file, for example, User.feature and there I would put test scenarios like: Add user, Remove user etc.

2024-08-05 06:58 UTC, al-kai commented on src/test/resources/features/add_user.feature
> +  Background:
If there's nothing in the Background, line should be removed.

2024-08-05 06:58 UTC, al-kai commented on src/test/resources/features/add_user.feature
> +  Scenario: Check user is successfully added to the list of users
I think it should be: Scenario: Add new user to the list of users

2024-08-05 06:58 UTC, al-kai commented on src/test/resources/features/remove_user.feature
> +  Scenario: Check user is successfully removed from the list of users
I'd suggest changing it to - Scenario: Remove user form the list of users

2024-08-05 06:58 UTC, al-kai commented on src/test/resources/features/update_user.feature
> +  Scenario: Check user details are successfully changed
I'd suggest changing it to - Scenario: Update user details

2024-08-05 06:58 UTC, al-kai commented on src/test/resources/features/view_details.feature
> +  Scenario: Check user is successfully added to the list of users
Same as above. I'd suggest changing it to - Scenario: View user details.
There's also another way of updating user data you haven't tested yet. Maybe also worth looking at?

2024-08-05 06:58 UTC, al-kai commented on src/test/java/StepDefinitions/AddUserStep.java
> +    AddUserPage addUserPage;
I'd rather initialise the object once at the beginning of the step class and not in the method. Later if needed, it's easily accessible by all methods.

2024-08-05 06:58 UTC, al-kai commented on src/test/java/StepDefinitions/AddUserStep.java
> +    @When("user clicks add new user")
Please correct indentation :)

2024-08-05 06:58 UTC, al-kai commented on src/test/resources/features/add_user.feature
> +    And fills in the details
I'd change to -> And new user's data is filled

2024-08-05 06:58 UTC, al-kai commented on src/test/resources/features/add_user.feature
> +    And confirms the user creation
Maybe And new user's creation is confirmed

2024-08-05 06:58 UTC, al-kai commented on src/test/resources/features/add_user.feature
> +    Given user is on the main page
Also another thing I'd suggest is having a preparation step for the new user data, for example, And new user data is prepared. Here we could randomise users data using, for example, easy random.

2024-08-05 06:58 UTC, al-kai commented on src/test/java/StepDefinitions/AddUserStep.java
> +    addUserPage.addNewUser("Adam", "Malysz", "am@kainos.com", "Junior Developer");
Instead of hardcoding user data, I'd create User model and I'd randomise the values inside. This could be done in the step And new user's data is prepared. Then the object can be used as a source of values for addNewUser().

2024-08-05 06:58 UTC, al-kai commented on src/test/java/utils/User.java
> +}
The data model should be moved to a separate directory dataModels and should be the same as the one in the readme file so there should be name, surname, email and position.

2024-08-05 06:58 UTC, al-kai commented on src/test/java/StepDefinitions/AddUserStep.java
> +    addUserPage = new AddUserPage(driver);
You should avoid using hardcoded values. You could get those values from User stored in keys.

2024-08-05 06:58 UTC, al-kai commented on src/test/java/StepDefinitions/AddUserStep.java
> +public void userPresence(String name, String surname) {
Same as above ^

2024-08-05 06:58 UTC, al-kai commented on src/test/java/StepDefinitions/CommonStep.java
> +        assertTrue(driver.getTitle().contains("Journey Blog"));
Maybe this value could be extracted to a constant as MAIN_PAGE_TITLE?

2024-08-05 06:58 UTC, al-kai commented on src/test/java/StepDefinitions/RemoveUserStep.java
> +        assertTrue(!bodyText.contains("Adam Malysz"));
Same as before regarding hardcoded values.

2024-08-05 06:58 UTC, al-kai commented on src/test/java/Pages/MainPage.java
> +    public MainPage addUser() {
If the method is just about clicking the element on the page, I'd change the name of the method to, for example, clickAddUserLink() etc.

2024-08-05 06:58 UTC, al-kai commented on src/test/java/StepDefinitions/UpdateUserStep.java
> +        addUserPage.addNewUser("Bob", "Ross", "bros@kainos.com", "Senior Developer");
Same as before regarding hard-coded values.

Also this feels a bit like adding a completely new user rather than updating the existing one. Maybe you could change, for example, just the email? And then check that it has been changed.

2024-08-05 06:58 UTC, al-kai commented on src/test/java/StepDefinitions/RemoveUserStep.java
> +    public void addUser() {
method name a bit confusing - are we removing or adding the user?

2024-08-05 06:58 UTC, al-kai commented on src/test/java/Pages/MainPage.java
> +    //private List<User> users = new ArrayList<>();
Commented code should be removed

2024-08-05 06:58 UTC, al-kai commented on src/test/java/StepDefinitions/ViewDetailsStep.java
> +        Assert.assertTrue(bodyText.contains("utils.context.User details"), "utils.context.User details shown successfully");    }
I'd rather focus on the table to check that the user data is correct.

2024-08-05 06:58 UTC, al-kai commented on src/test/java/StepDefinitions/UpdateUserStep.java
> +        Assert.assertTrue(bodyText.contains("Bob Ross"), "utils.context.User update successful");
Here you're just checking the name of the person and what about the other data that have been changed? Again the data is in a table, maybe worth trying to extract the data from the table?

2024-08-05 06:58 UTC, al-kai commented on src/test/java/API/BackendTest.java
> +
As far as I know, the API tests should also use the same convention as the UI tests.

2024-08-06 12:29 UTC, jakubrkainos requested changes

2024-08-06 12:29 UTC, jakubrkainos commented on src/test/java/API/BackendTest.java
> +given()
Can you create a service class that will contain all the interactions with the API? Also we will need Validator class to validate the responses.

2024-08-06 12:29 UTC, jakubrkainos commented on src/test/java/API/BackendTest.java
> +given()
Also it will be good to use Cucumber instead of pure JUnit

2024-08-06 12:29 UTC, jakubrkainos commented on src/test/java/Pages/MainPage.java
> +    public void userTable(){
This method is not doing anything. Also name is not understandable.

2024-08-06 12:29 UTC, jakubrkainos commented on src/test/java/Pages/MainPage.java
> +        return this;
Always return new page object of the page you are going to be taken.

2025-01-21 14:39 UTC, merged